services:
  - type: web
    name: proyecto-restaurante-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd Backend && gunicorn Backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto-restaurante-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: proyecto-restaurante-db
    databaseName: proyecto_restaurante
    user: proyecto_restaurante
